### ISSUE TITLE
Global slash commands

### ISSUE THREAD

**Issue by ddugovic** [edderiofer/YACP-Bot#4] opened 2022-07-31 17:34 UTC
`/help` etc. seem to be missing in my server.

**Comment by edderiofer** [comment] 2022-07-31 17:52
Should be temporarily fixed now. My suspicion is that this is caused by running multiple instances of the bot then closing the latest-started instance. (But I don't immediately have proof of this.)

If that's the case, then this should probably end up proper fixed once I end up hosting this bot somewhere where I don't really have to touch it.

**Closed as completed** 2022-07-31 18:51 UTC
